### ISSUE TITLE
Vertical slides

### ISSUE THREAD

**Issue by asalber** [planetoftheweb/rayveal#11]
Hi, I like your tuned version of reveal.js, but is it possible to create vertical slides, that is arrange slides in two dimensions?
Thanks!

**Comment by planetoftheweb** [comment]
Yes, although I don't use them. It uses theme revealjs script so it does everything it can do

**Comment by asalber** [comment]
Yes, I know it. But, which separator should I use in my markdown file to arrange a slide vertically?
Thanks!

**Comment by asalber** [comment]
Yes, I know it. But, which separator should I use in my markdown file to
arrange a slide vertically?
Thanks!

**Comment by planetoftheweb** [comment]
The default is set in the index.html file.

Look for this code
```
<div class="slides">
  | <section
  | data-markdown="slides/demo.md"
  | data-separator="\n---\n"
  | data-separator-vertical="^\n\n"
  | data-separator-notes="\n> >"
  | data-charset="iso-8859-15"
  | ></section>
  | </div>
```

As I said, I don't use it, but it looks like a caret and a couple of carriage returns, or you can configure it however you like.

Here's the page in the docs: https://revealjs.com/markdown/
