### ISSUE TITLE
How to change layout as code on the right and text on the left

### ISSUE THREAD

**Issue by SF001User** [planetoftheweb/rayveal#23]
Thanks a lot for this awesome template, it has been very useful.
I would appreciate it if you can provide guidance on arranging items like code block and explanations text side by side. 
I have tried few bootsrap classes, it seems to have no effect on the layout. 

Thanks in advance.

**Comment by planetoftheweb** [comment]
There's already a layout called mostly image: https://rayveal.tech/#/18/0/0



So you can use that or look at the code to see how to arrange things side by side. It's specially difficult. Glad you're enjoying it.
